---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: ca-secret-per-cluster
spec:
  resyncPeriodSeconds: 60
  resources:
  - apiVersion: cluster.x-k8s.io/v1beta1
    resource: clusters
  attachments:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://ca-secret-controller/sync
    customize:
      webhook:
        url: http://ca-secret-controller/customize
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-secret-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-secret-controller
  template:
    metadata:
      labels:
        app: ca-secret-controller
    spec:
      containers:
      - name: controller
        image: python:3.9
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: ca-secret-controller
---
apiVersion: v1
kind: Service
metadata:
  name: ca-secret-controller
  namespace: metacontroller
spec:
  selector:
    app: ca-secret-controller
  ports:
  - port: 80