apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: ca-trust-service.fling.vsphere.vmware.com
spec:
  displayName: ca-trust-service
  longDescription: ca-trust-service.fling.vsphere.vmware.com
  shortDescription: ca-trust-service.fling.vsphere.vmware.com
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: ca-trust-service.fling.vsphere.vmware.com.1.0.1
spec:
  refName: ca-trust-service.fling.vsphere.vmware.com
  releasedAt: "2024-01-26T20:52:40Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/ca-trust-service@sha256:6886864ec67b0c538a13f31109137fb5863201f932346be574451a6c0e84e599
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.0.1
