apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: ca-trust-service.fling.vsphere.vmware.com
spec:
  displayName: ca-trust-service
  longDescription: ca-trust-service.fling.vsphere.vmware.com
  shortDescription: ca-trust-service.fling.vsphere.vmware.com
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: ca-trust-service.fling.vsphere.vmware.com.1.0.4
spec:
  refName: ca-trust-service.fling.vsphere.vmware.com
  releasedAt: "2024-01-31T01:50:13Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/ca-trust-service@sha256:d3558a09e622cf275b7c98f7c710c6529c1f46713c435fb38b90d248881722b9
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.0.4
